version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - dupl
    - gosec
    - misspell
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
  disable:
    - gochecknoglobals
    - lll
    - wsl
    - errcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G107
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
          severity: warning
          disabled: false
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gosec
        path: _test\.go
      - linters:
          - gosec
        text: "G404: Use of weak random number generator"
      - linters:
          - all
        path: test/mocks/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - pkg/sync/syncer.go
