name: Workflow Configuration

# This file stores shared configuration variables for all workflows
# Other workflows can use these values for consistency

env:
  GO_VERSION: "1.23"
  NODE_VERSION: "18"
  DOCKER_REGISTRY: "docker.io"
  DOCKER_IMAGE: "yugasun/hubsync"
  
  # Build matrix configurations
  BUILD_PLATFORMS: |
    {
      "goos": ["linux", "darwin", "windows"],
      "goarch": ["amd64", "arm64"],
      "exclude": [
        {"goos": "windows", "goarch": "arm64"}
      ]
    }