name: Build and Push Docker Image

on:
  # Only run on tag pushes or manual triggers
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (with v prefix, e.g., v1.2.3)'
        required: false
        type: string
      skip_if_exists:
        description: 'Skip build if image already exists'
        required: false
        default: true
        type: boolean

jobs:
  # Check if Docker image already exists
  check-image:
    runs-on: ubuntu-latest
    outputs:
      image_exists: ${{ steps.check.outputs.exists }}
      should_build: ${{ steps.decision.outputs.should_build }}
    steps:
      - name: Extract version
        id: extract
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="dev"
          fi
          
          # Remove 'v' prefix for Docker tags
          DOCKER_TAG="${VERSION#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "docker_tag=$DOCKER_TAG" >> $GITHUB_OUTPUT

      - name: Check if image already exists
        id: check
        continue-on-error: true
        run: |
          # Check if image exists in Docker Hub registry
          EXISTS="false"
          DOCKER_TAG="${{ steps.extract.outputs.docker_tag }}"
          
          STATUS=$(curl --silent -f -L -o /dev/null -w "%{http_code}" \
            https://hub.docker.com/v2/repositories/${{ env.DOCKER_IMAGE }}/tags/$DOCKER_TAG)
          
          if [ "$STATUS" = "200" ]; then
            EXISTS="true"
            echo "Image ${{ env.DOCKER_IMAGE }}:$DOCKER_TAG already exists in Docker Hub"
          else
            echo "Image ${{ env.DOCKER_IMAGE }}:$DOCKER_TAG does not exist in Docker Hub"
          fi
          
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT
      
      - name: Decide whether to build
        id: decision
        run: |
          # Determine if we should build
          SHOULD_BUILD="true"
          
          # Skip if image exists and skip_if_exists is true
          if [[ "${{ steps.check.outputs.exists }}" == "true" && "${{ inputs.skip_if_exists }}" == "true" ]]; then
            SHOULD_BUILD="false"
            echo "Skipping build as image already exists and skip_if_exists=true"
          fi
          
          # Always build for PRs (for testing)
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            SHOULD_BUILD="true"
            echo "Always building for pull requests (for testing)"
          fi
          
          echo "should_build=$SHOULD_BUILD" >> $GITHUB_OUTPUT
          
          if [[ "$SHOULD_BUILD" == "false" ]]; then
            echo "::warning::Skipping Docker build for version ${{ steps.extract.outputs.version }} - image already exists"
          fi

  build-and-push:
    needs: check-image
    if: needs.check-image.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    # Use the shared configuration values
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_IMAGE: yugasun/hubsync
      PLATFORMS: linux/amd64,linux/arm64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for git describe to work properly
          ref: ${{ inputs.version || github.ref }}
      
      - name: Extract version information
        id: version
        run: |
          # If version was provided via workflow_dispatch
          if [ -n "${{ inputs.version }}" ]; then
            GIT_VERSION="${{ inputs.version }}"
            echo "Using provided version: $GIT_VERSION"
          # Determine version from git tags or from tag event
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            GIT_VERSION=${GITHUB_REF#refs/tags/}
            echo "Using tag version: $GIT_VERSION"
          else
            GIT_VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
            echo "Using git-derived version: $GIT_VERSION"
          fi

          echo "GIT_VERSION=${GIT_VERSION}" >> $GITHUB_ENV
          echo "VERSION=${GIT_VERSION#v}" >> $GITHUB_ENV  # Remove 'v' prefix for Docker tags
          
          # Set short SHA for dev builds
          if [[ "$GIT_VERSION" == "dev" ]]; then
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
            echo "DEV_TAG=dev-${SHORT_SHA}" >> $GITHUB_ENV
          fi

          echo "git_version=${GIT_VERSION}" >> $GITHUB_OUTPUT
          echo "Version extracted: ${GIT_VERSION}"

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest,enable=${{ env.VERSION != 'dev' && !contains(env.VERSION, '-') }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.VERSION }}
            type=semver,pattern={{major}},value=${{ env.VERSION }}
            type=raw,value=${{ env.DEV_TAG }},enable=${{ env.GIT_VERSION == 'dev' }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            VERSION=${{ env.GIT_VERSION }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            COMMIT_SHA=${{ github.sha }}
      
      # This step is necessary to prevent cache from growing indefinitely
      - name: Move cache
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Verify Docker image
        if: github.event_name != 'pull_request'
        run: |
          echo "Verifying published Docker image..."
          DOCKER_TAG="${{ env.VERSION }}"
          
          # For dev builds use the dev tag
          if [[ "${{ env.GIT_VERSION }}" == "dev" ]]; then
            DOCKER_TAG="${{ env.DEV_TAG }}"
          fi
          
          # Wait a moment for Docker Hub to process the image
          sleep 10
          
          # Pull the image to verify it exists and is accessible
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:$DOCKER_TAG || \
            echo "Warning: Unable to verify image. It may still be processing on Docker Hub."
          
          # Report success
          echo "Docker image published: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:$DOCKER_TAG"
